web:
  build: .
  ports:
  - "80:3000"
  volumes:
  - .:/usr/src/app/:rw

  command: >
    sh -c '
      if test -d node_modules;
      then
        echo node_modules_exists ;
      else
        cp -a /tmp/node_modules /usr/src/app/website;
      fi &&
      npm install &&
      /usr/local/bin/node/output ./myCode.js
    '
